### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by thewizster** [jmhdez/TinyTwitter#4]
Thanks for providing TinyTwitter. I am attempting my first twitter app and found it a simple way to get started.

I have added TinyTwitter.cs to my console application.

I am attempting to get your sample to work but have problems with this.
var tweets = twitter.GetHomeTimeline();

I am getting 403 error:
System.Net.WebException: The remote server returned an error: (403) Forbidden.
  at at System.Net.HttpWebRequest.GetResponse()
  at at TinyTwitter.TinyTwitter.RequestBuilder.Execute()

Any insight you could provide would be greatly appreciated.

**Comment by jmhdez** [comment]
It looks like some authentication problem, I'd check the authentication tokens.

You could also use something like Fiddler to see if there is more info in the server response.

**Comment by seeseekey** [comment]
Same problem here. Other operations like UpdateStatus() still works. The detailed JSON answer (in the 403) is: {"errors":[{"message":"SSL is required","code":92}]}

**Comment by seeseekey** [comment]
The api url starts now with https (https://dev.twitter.com/rest/reference/get/statuses/home_timeline). But TinyTwitter uses http in GetHomeTimeline(), GetMentions() and GetUserTimeline().

**Comment by seeseekey** [comment]
I create a pull request with a fix of this issue.

**Comment by jmhdez** [comment]
Merged, thanks!

**Comment by MistressPlague** [comment]
Still having this issue with GetUserTimeline - Can someone test this to see if it is on my end? Thanks!
