### ISSUE TITLE
Dual-licensed under MIT

### ISSUE THREAD

**Issue by seeseekey** [jmhdez/TinyTwitter#7]
Hi,

i would ask if it possible is to dual-licence the library under MIT and Apache license (or only MIT-License)?

Sincery,

Florian

**Comment by jmhdez** [comment]
Why?

(Just curious, I don't mind to change the license)

**Comment by seeseekey** [comment]
The reason is the posibility to relicensing the code unter other free licenses. From the MIT licence you can relicensing the code to modified BSD, Apache, LGPL, GPL and AGPL. From the apache license you can relicensing the code only to LGPL 3, GPL3 and AGPL 3.

**Comment by jmhdez** [comment]
Ok, I see.

I don't have access to a reliable connection on this moment, but I will
change the license as soon as I can. If you need to change the license
meanwhile, feel free to do it as if current license were MIT.

Hope this helps.
